### ISSUE TITLE
Projects sehifesinin hazirlanmasi

### ISSUE THREAD

**Issue by goshgarmirzayev** [bsp-tech/itcommunity#2]

**Comment by goshgarmirzayev** [comment]
Video'da nece olacagi haqqinda melumat verilir
https://www.youtube.com/watch?v=4X1boJe9t-M&feature=youtu.be

**Comment by bsptech** [comment]
Bu issue-da ne problem var ki? Yeniden reopen olunub 8 gun onceden.
