### ISSUE TITLE
TASK-15 - FRONT - Employee Details

### ISSUE THREAD

**Issue by bsptech** [bsp-tech/itcommunity#28]
Diagramda izah edilir tapşırıq. Sualın olsa comment yazarsan.

https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Employee.drawio#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1LZVu4sjtup0NA56FFspurbqIFhrjTkQf%26export%3Ddownload

WARNING: PR yaradanda 

master <-  TASK-15 

şəklində yaradarsan

**Comment by azarmuradli** [comment]
Belə olduqda details buttonunu silməliyəm.Lazım olmayacaq
