### ISSUE TITLE
TASK-5 qeydiyyat sehifelerinnin hazirlanmasi

### ISSUE THREAD

**Issue by kamilasgarov** [bsp-tech/itcommunity#5]

**Comment by goshgarmirzayev** [comment]
Burada  isWorking field,isLookingForWork text iput deyil checkbox ve ya select  olmalidi. Skill ve langueage  fieldlari 
![image](https://user-images.githubusercontent.com/35040732/63831426-ad7a1700-c97f-11e9-8e45-0a65bb45bdc1.png) Seklinde olsun

**Comment by goshgarmirzayev** [comment]
User registrationda Male ve ya female olsan checkboxlar yigisdirilib selectbox qoyulsun. Email Input age'den sonra otursun asagi

**Comment by kamilasgarov** [comment]
*Other languageni yigisdirilsin
* is working select boxu. yes ve no olsun
*skills and language level 1-10 araliqi olsun
*scripti yeri duzeldilsin meselene ../js falan
*iconlar duzeldilsin @azarmuradli
