### ISSUE TITLE
TASK-4 login sehifesi

### ISSUE THREAD

**Issue by kamilasgarov** [bsp-tech/itcommunity#6]

**Comment by bsptech** [comment]
![WhatsApp Image 2019-08-30 at 01 48 48](https://user-images.githubusercontent.com/53878973/63979770-ba575180-caca-11e9-99ac-1cf9d9438f9d.jpeg)

Login bu shekildeki kimi olsun.Sadece ashagidaki deyishiklikler de olsun.

1. username xanasinda yazilacaq Email
2. Login with email yox login with gmail olacaq ve gmailin iconu olacaq (dizaynina baxarsa mence Login ve Login with gmail alt alta olsa yaxshidir)
